org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false
net.minecraftforge.gradle.merge-source-sets=true

mod_version=0.3.0.2603001
mod_group=zone.moddev.mc
mod_archive_name=iron-age-furniture-biomes-o-plenty-addon
mod_id=iafbopaddon
mod_name=Iron Age Furniture Biomes O' Plenty Add-on
mod_description=Adds Biomes O' Plenty wood furniture to Iron Age Furniture.
mod_authors=SkyBlade1978, FoxNekitsune
mod_license=LGPL-2.1

minecraft_version=26.3
minecraft_version_range=[26.3]
loader_name=forge
loader_code=1
java_version=25
java_toolchain_version=25.0.3+9
java_setup_version=25.0.3+9.0.LTS
gradle_java_version=25
forge_version=66.0.2
forge_version_range=[66.0.2,67)
loader_version_range=[66,)
mcp_mappings_channel=official
mcp_mappings_version=26.3

ironagefurniture_version=0.3.0.2603001
ironagefurniture_version_range=[0.3.0.2603001,0.4)
ironagefurniture_sha256=38445f20b7a1083840c92f9d15033117ed55ad1dc2dd75d564aa4ccf2381b3d4
biomesoplenty_version=26.3.0.0.4
biomesoplenty_version_range=[26.3.0.0.2,26.4)
biomesoplenty_minimum_version=26.3.0.0.2
biomesoplenty_minimum_sha256=330f2df1dfd19e33c609348984eef19e8ace63f6753b056459b598add3a4aa38
biomesoplenty_sha256=188b87325486b003036dbdb2f1996eabc320628cbed58608dd8fbb23d2488e8a
glitchcore_version=26.3.0.0.3
glitchcore_sha256=8a13afb2f8035a527e3927c3fda76bb0f889d57ea8ddf2d0926d4bc02a790152
terrablender_version=26.3.0.0.5
terrablender_sha256=926a4399d3c092b2a2d4f8626c4d4e482448217f59e86e38c7e661c33b34a846
terrablender_current_version=26.3.0.0.6
terrablender_current_sha256=39733452924944aa5da5f8e033dcb2d4a435d141faf356934d0901d8c42b6e19

# Iron Age Furniture Biomes O' Plenty Add-on on CurseForge.
curseforge_project_id=1705705
curseforge_required_dependencies=iron-age-furniture,biomes-o-plenty
