org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false

mod_version=0.3.0.2603002
mod_group=zone.moddev.mc
mod_archive_name=iron-age-furniture-biomes-o-plenty-addon
mod_id=iafbopaddon
mod_name=Iron Age Furniture Biomes O' Plenty Add-on
mod_description=Adds Biomes O' Plenty wood furniture to Iron Age Furniture.
mod_authors=SkyBlade1978, FoxNekitsune
mod_license=LGPL-2.1

minecraft_version=26.3
minecraft_version_range=[26.3]
loader_name=neoforge
loader_code=2
java_version=25
java_toolchain_version=25.0.3+9
java_setup_version=25.0.3+9.0.LTS
gradle_java_version=25
neo_version=26.3.0.1-beta
neo_version_range=[26.3.0.1-beta,26.3.1)

ironagefurniture_version=0.3.0.2603002
ironagefurniture_version_range=[0.3.0.2603002,0.4)
ironagefurniture_sha256=418c546febcc5d1ab673de9e6642ffdb30177a100d935e915af3ace9f013f74e
biomesoplenty_version=26.3.0.0.2
biomesoplenty_version_range=[26.3.0.0.2,26.4)

# Iron Age Furniture Biomes O' Plenty Add-on on CurseForge.
curseforge_project_id=1705705
curseforge_required_dependencies=iron-age-furniture,biomes-o-plenty
